version: 2.1

jobs:
  build-app:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
         keys: [build-application]
      - run:
         name: Install dependencies
         command: |
           make install 
      - run:
         name: copy project files
         command: |
            sudo cp ./config/nginx.conf /etc/nginx/nginx.conf
            sudo cp -r ./www /www
      - run:
         name: build app
         command: |
           make build
      - run:
         name: test app
         command: |
           make test
      - save_cache:
         paths: [node_modules]
         key: build-application

  lint-app:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: lint on app
         command: |
            make lint
            
         
workflows:
  default:
    jobs:
      - build-app
      - lint-app
            requires: [build-app]