version: 2.1

jobs:
  build-app:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
         keys: [build-application]
      - run:
         name: Install dependencies
         command: |
           make install 
      - run:
         name: copy project files
         command: |
            make copy
      - run:
         name: build app
         command: |
           make build
      - run:
         name: test app
         command: |
           make test
      - save_cache:
         paths: [node_modules]
         key: build-application
         
workflows:
  default:
    jobs:
      - build-app
